<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ecompc"
 *
 * Auto generated by Extension Builder 2014-07-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['ecompc'] = array(
	'title' => 'Product Configurator',
	'description' => 'A more or less complex product configuration enabling the user to configure their specific product with output of an article number or a dynamic configuration code, based on options checked.',
	'category' => 'plugin',
	'author' => 'Sebastian Iffland',
	'author_email' => 'sebastian.iffland@ecom-ex.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '0.2.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'php' => '5.4.0-5.5.99'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);